repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.7.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.33.0
    hooks:
      - id: ggshield
        language_version: python3
        stages: [ pre-commit ]
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: uv run pytest tests
        language: system
        pass_filenames: false
        always_run: true
