[tool.poetry]
name = "ingest-wikimedia"
version = "0.1.0"
description = "Uploading media to Wikimedia Commons"
authors = ["Scott Williams <scott@dp.la>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
pywikibot = "^7.1.0"
certifi = "^2021.10.8"
urllib3 = "^1.26.9"
awswrangler = "^2.15.1"
python-magic = "^0.4.25"
fastparquet = "^0.8.1"
s3fs = "^2022.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
