[tool.poetry]
name = "ingest-wikimedia"
version = "0.1.0"
description = "Uploading media to Wikimedia Commons"
authors = ["Scott Williams <scott@dp.la>, Michael Della Bitta <michael@dp.la>"]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
pywikibot = "^9.2.0"
certifi = "^2024.06.2"
urllib3 = "^2.2.2"
awswrangler = "^3.8.0"
python-magic = "^0.4.27"
fastparquet = "^2024.5.0"
s3fs = "^2024.6.0"
mwparserfromhell = "^0.6.6"
validators = "^0.28.3"
requests = "^2.32.3"

[tool.poetry.dev-dependencies]
black = "^24.4.2"
flake8 = "^7.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
